### ISSUE TITLE
Add "Last 30 Seconds" Button to FLAC Player

### ISSUE THREAD

**Issue by ThisIsMarkAdams** [Syco54645/TagBot#27]
It would be nice to implement a button that skips to the last thirty seconds of a file to assist in tagging for songs that may have teases at the end, etc.

**Comment by Syco54645** [comment]
Should this functionality just be rolled into the 30 second skip button? It could just always skip to the last 30 seconds if time remaining < 30 seconds.

**Comment by ThisIsMarkAdams** [comment]
Possibly, but you could end up pressing that button forever at times depending on the length of the song and you never really know how close you are.

**Comment by Syco54645** [comment]
Yeah that was my concern with doing it that way. Any suggestions on what the button should look like?

**Comment by ThisIsMarkAdams** [comment]
Perhaps it could look as follows... >|

**Comment by Syco54645** [comment]
I was thinking that with a 30 on it. I will mess around and try to find
something.
